# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "api-throttling"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Luc Castera", "John Duff"]
  s.date = "2012-07-16"
  s.description = "Rack Middleware to impose a rate limit on a web service (aka API Throttling)"
  s.email = "duff.john@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "LICENSE",
    "README.md",
    "Rakefile",
    "TODO.md",
    "VERSION.yml",
    "api-throttling.gemspec",
    "config.ru",
    "lib/api_throttling.rb",
    "lib/handlers/active_support_cache_store_handler.rb",
    "lib/handlers/handlers.rb",
    "lib/handlers/hash_handler.rb",
    "lib/handlers/memcache_handler.rb",
    "lib/handlers/redis_handler.rb",
    "test/test_api_throttling.rb",
    "test/test_api_throttling_hash.rb",
    "test/test_api_throttling_memcache.rb",
    "test/test_handlers.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/jduff/api-throttling/tree"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Rack Middleware to impose a rate limit on a web service (aka API Throttling)"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<context>, [">= 0"])
    else
      s.add_dependency(%q<context>, [">= 0"])
    end
  else
    s.add_dependency(%q<context>, [">= 0"])
  end
end

